<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>P7m.Engine.Graphics</RootNamespace>
    <Description>Host gráfico MonoGame da engine P7M: pipeline deferred 2D (MRT), vertex shader de Linear Blend Skinning e câmera cinemática aplicada à projeção</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../P7m.Engine.Core/P7m.Engine.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Shaders/**/*.fx" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content/Content.mgcb" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
